[tool.poetry]
name = "tokun"
version = "0.7.2"
description = "NN model specialized in text embedding."
authors = ["apehex <apehex@protonmail.com>"]
readme = ".github/README.md"

[tool.poetry.dependencies]
mlable = ">=0.3"
python = ">=3.10, <3.12"
tensorflow = ">=2.14"
tensorflow-datasets = ">=4.9"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
